server:
  port: 8082

spring:
  application:
    name: auth-service

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret-key: a-string-secret-at-least-256-bits-long
  expiration: 3600000  # 1시간 (밀리초)

user-service:
  url: http://localhost:8081

#cors:
#  allowedOrigins: http://localhost:5173

