spring:
  application:
    name: auth-service

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    discovery:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8082

user-service:
  url: http://localhost:8081

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
  endpoint:
    busrefresh:
      enabled: true
  security:
    enabled: false