spring:
  application:
    name: live-streaming-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-service:8888}

server:
  port: 8096