spring:
  application:
    name: notification-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8096