spring:
  application:
    name: LIVE-STREAMING-SERVICE

  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: ["refresh", "busrefresh", "prometheus", "health", "info"]
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    metrics:
      export:
        prometheus:
          enabled: true
      tags:
        application: ${spring.application.name}
  security:
    enabled: false