server:
  port: 8093

spring:
  application:
    name: PRODUCT-SERVICE

  datasource:
    url: jdbc:mariadb://localhost:3306/shopmall
    username: kosa
    password: 1004
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh
  endpoint:
    busrefresh:
      enabled: true
  security:
    enabled: false

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
