spring:
  application:
    name: commerce-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}  # localhost로 변경

server:
  port: 8090
