spring:
  application:
    name: eureka-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-service:8888}

server:
  port: 8761

# Config Server 연결 실패시 기본 설정
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    tls:
      enabled: false