server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/fhohf/config-repo

encrypt:
  key-store:
    location: file:/apiEncryptionKey.jks
    password: test1234
    alias: apiEncryptionKey

management:
  endpoints:
    web:
      exposure:
        include: ["refresh", "busrefresh", "prometheus", "health", "info"]
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    metrics:
      export:
        prometheus:
          enabled: true
      tags:
        application: ${spring.application.name}