server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}  # native로 변경
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_PATH:file:///C:/Users/fhohf/config-repo}
        # git 설정 완전히 제거 (빈 문자열이 문제 원인)

# 암호화 설정
encrypt:
  key-store:
    location: ${ENCRYPT_KEYSTORE_LOCATION:file:/apiEncryptionKey.jks}
    password: ${ENCRYPT_KEYSTORE_PASSWORD:test1234}
    alias: ${ENCRYPT_KEYSTORE_ALIAS:apiEncryptionKey}

management:
  endpoints:
    web:
      exposure:
        include: ["refresh", "busrefresh", "health", "info", "env"]
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.kosa.configservice: DEBUG