server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native  # 개발환경 기본값
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/fhohf/config-repo
        encrypt:
          enabled: false  # 암호화 비활성화

management:
  endpoints:
    web:
      exposure:
        include: ["refresh", "busrefresh", "health", "info", "env"]
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.kosa.configservice: DEBUG

---
# 운영환경 설정
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
          default-label: main
          clone-on-start: true

security:
  user:
    name: ${CONFIG_SERVER_USERNAME:config}
    password: ${CONFIG_SERVER_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
  security:
    enabled: true

logging:
  level:
    org.springframework.cloud.config: INFO