server:
  port: 8888

spring:
  application:
    name: config-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}

  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_REPO_PATH:file:///C:/Users/fhohf/config-repo}
        # Git 사용하는 경우 (운영환경 권장)
        git:
          uri: ${CONFIG_REPO_GIT_URI:https://github.com/your-username/config-repo.git}
          default-label: main
          clone-on-start: true
          force-pull: true

# 암호화 설정 (기존 유지)
encrypt:
  key-store:
    location: ${ENCRYPT_KEYSTORE_LOCATION:file:/apiEncryptionKey.jks}
    password: ${ENCRYPT_KEYSTORE_PASSWORD:test1234}
    alias: ${ENCRYPT_KEYSTORE_ALIAS:apiEncryptionKey}

management:
  endpoints:
    web:
      exposure:
        include: ["refresh", "busrefresh", "prometheus", "health", "info", "env"]
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
    metrics:
      export:
        prometheus:
          enabled: true
      tags:
        application: ${spring.application.name}

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.kosa.configservice: DEBUG