server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
       native:
         search-locations: file://${user.home}///c:\Users\fhohf\native-file-repo

  profiles:
    active: native
