spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/fhohf/config-repo

management:
  endpoints:
    web:
      exposure:
        include: ["refresh", "busrefresh", "health", "info", "env", "prometheus"]
  endpoint:
    prometheus:
      enabled: true
    metrics:
      export:
        prometheus:
          enabled: true
  security:
    enabled: false
