server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        native:
          search-locations: file:///c:/Users/fhohf/config-repo

  profiles:
    active: native